---
- name: change ssh port, edit security group
  hosts: "{{host}}"
  tasks:
    - name: Change ssh port on a given host
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "{{item}}"
      with_items:
        - "Port {{port}}"
        - "Port 22"

    - name: allow sshd to listen on given tcp port
      seport:
        ports: "{{port}}"
        proto: tcp
        setype: ssh_port_t
        state: present

    - name: restart sshd
      systemd:
        name: sshd
        state: restarted

    - name: get the hosts security group
      ec2_instance_facts:
        region: eu-west-1
      delegate_to: localhost
      register: segroup

    - set_fact:
        #ip="{{item.private_ip_address}}"
        sg="{{item.security_groups[0].group_name}}"
      when: item.private_ip_address == ansible_default_ipv4.address
      with_items: "{{segroup.instances}}"

    - name: add a rule to a security group, that allows a connection through a given port
      ec2_group:
        name: "{{sg}}"
        description: awx_host
        region: eu-west-1
        purge_rules: false
        rules:
          - proto: tcp
            ports:
              - "{{port}}"
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all tcp on port 
      delegate_to: localhost 
    
    - name: check if port is open
      wait_for:
        host: "{host{}}"
        port: "{{port}}"
        delay: 5
        timeout: 10
        msg: "Timeout waiting for ssh connection on a given port"
      ignore_errors: yes
      register: port_check

    - name: print the error message if the port is not open
      when: port_check.failed|bool
      debug:
        msg: "ssh connection to port port failed"

    - name: print message saying that port was succeddfully opened
      when: not port_check.failed|bool
      debug:
        msg: "ssh connection to port port succeeded"